### PR TITLE
Add Custom Header to UnivapayClientOptions

### PR DESCRIPTION
**Pull request by wrunivapay**
This is the basic implementation to add custom headers for all request's url

### CODE REVIEW

**Comment by wrunivapay** [comment]
@kgston This is the idea of the implementation so we can customize headers like below:
```
$clientOptions = new UnivapayClientOptions(
"http/s://xxx.xxx.xxx.xxx:xxx”, [
    'custom_xxx' => ‘xxx’,
    'custom_xxx' => ‘xxx’,
]);
$token = AppJWT::createToken(‘token’, ‘secret’);
$client = new UnivapayClient($token, $clientOptions);
```

**Comment by kgston** [comment]
I think you mentioned that the use case for this is to override the `host` header. Could you show me specifically what endpoint you are defining and what host header do you need to set?

**Comment by wrunivapay** [comment]
Atm it was `getCharge` with the endpoint `/stores/:storeId/charges/:chargeId` and `getSubscription` with the endpoint `/stores/:storeId/subscriptions/:subscriptionId`. The header used is `Host`.

I believe most other API calls will be denied because of my environments between the client (container) and the API (host). Setting up the API to allow that would be the easiest solution, but adding custom headers on the client is another option we could consider.

**Comment by wrunivapay** [comment]
@kgston Apologize for not providing the background earlier. The issue only occurs in local development mode when all services are run locally. In this scenario, domain validation fails because the container needs to call the API using the local domain or host IP.

However, after further consideration, I realized that this approach does not benefit the end client...
Therefore, I will close this issue.

**Pull request closed without merging**
